/* ================================================================
 * main_app.c
 *
 * Application entry point.
 * Place the contents of the USER CODE sections into the
 * corresponding sections of the CubeMX-generated main.c.
 *
 * USER CODE BEGIN Includes:
 *   #include "channel_map.h"
 *   #include "radioroc2_i2c.h"
 *   #include "system_init.h"
 *   #include "timers.h"
 *   #include "daq.h"
 *   #include "compensation.h"
 *   #include "usb_comm.h"
 *
 * USER CODE BEGIN 2 (after HAL_Init and clock config):
 *   [startup sequence below]
 *
 * USER CODE BEGIN WHILE (main loop):
 *   [main loop below]
 * ================================================================ */

#include "main.h"
#include "channel_map.h"
#include "radioroc2_i2c.h"
#include "system_init.h"
#include "timers.h"
#include "daq.h"
#include "compensation.h"
#include "usb_comm.h"

/* External HAL handles generated by CubeMX */
extern I2C_HandleTypeDef  hi2c1;
extern ADC_HandleTypeDef  hadc1;
extern ADC_HandleTypeDef  hadc2;
extern TIM_HandleTypeDef  htim1;
extern TIM_HandleTypeDef  htim2;
extern TIM_HandleTypeDef  htim3;

/* ----------------------------------------------------------------
 * app_init — call from main() USER CODE BEGIN 2
 * ---------------------------------------------------------------- */
void app_init(void)
{
    /* 1. Initialise active channel list */
    channel_map_init();

    /* 2. Initialise I2C driver with HAL handle */
    radioroc2_i2c_init(&hi2c1);

    /* 3. Initialise compensation state */
    compensation_init();

    /* 4. Initialise USB communication */
    usb_comm_init();

    /* 5. Run full ASIC initialisation sequence */
    InitStatus_t init_result = system_init();

    if (init_result != INIT_OK) {
        /* Signal error — blink LED3 (PB0 on Nucleo-F722ZE) */
        while (1) {
            HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
            HAL_Delay(200);
        }
    }
}

/* ----------------------------------------------------------------
 * app_run — call from main() USER CODE BEGIN WHILE
 * ---------------------------------------------------------------- */
void app_run(void)
{
    while (1) {

        /* --------------------------------------------------------
         * EVENT PROCESSING
         * Flag set by EXTI0 ISR when NOR_T1OC falls.
         * -------------------------------------------------------- */
        if (g_event_pending) {
            daq_process_event();
        }

        /* --------------------------------------------------------
         * 1-SECOND TICK: temperature sampling + DAC feedback
         * -------------------------------------------------------- */
        if (timers_1s_elapsed()) {
            compensation_update_dac();
        }

        /* --------------------------------------------------------
         * HISTOGRAM TRIGGER CHECK
         * -------------------------------------------------------- */
        if (usb_comm_histogram_due()) {
            usb_comm_send_histogram_ready();
        }

        /* --------------------------------------------------------
         * INCOMING COMMANDS FROM PC
         * -------------------------------------------------------- */
        usb_comm_poll_commands();
    }
}
