/* ================================================================
 * usb_comm.c
 * ================================================================ */

#include "usb_comm.h"
#include "usbd_cdc_if.h"   /* generated by CubeMX USB CDC middleware */
#include <string.h>
#include <math.h>

/* ---------------------------------------------------------------
 * Global state
 * --------------------------------------------------------------- */
HistMode_t g_hist_mode  = HIST_MODE_COUNT;
uint32_t   g_hist_param = 1000;        /* default: 1000 events    */
float      g_s_t_ref    = S_T_REF;    /* runtime-updatable calib  */

static uint32_t s_event_count   = 0;
static uint32_t s_time_start_ms = 0;
static bool     s_hist_due      = false;

/* ---------------------------------------------------------------
 * Receive buffer — filled by USB CDC receive callback
 * --------------------------------------------------------------- */
#define RX_BUF_SIZE  32
static uint8_t  s_rx_buf[RX_BUF_SIZE];
static uint16_t s_rx_len = 0;
static bool     s_rx_ready = false;

/* ----------------------------------------------------------------
 * usb_comm_init
 * ---------------------------------------------------------------- */
void usb_comm_init(void)
{
    s_event_count   = 0;
    s_time_start_ms = HAL_GetTick();
    s_hist_due      = false;
    s_rx_ready      = false;
    s_rx_len        = 0;
}

/* ----------------------------------------------------------------
 * checksum — XOR of bytes 1 to n-1
 * ---------------------------------------------------------------- */
static uint8_t calc_checksum(const uint8_t *buf, uint8_t len)
{
    uint8_t cs = 0;
    for (uint8_t i = 0; i < len; i++) cs ^= buf[i];
    return cs;
}

/* ----------------------------------------------------------------
 * usb_comm_send_event
 *
 * Packet layout (7 bytes):
 *   [0] 0xAA          start byte
 *   [1] channel       0-63
 *   [2..5] keV        float, little-endian
 *   [6] checksum      XOR of bytes [1..5]
 * ---------------------------------------------------------------- */
void usb_comm_send_event(uint8_t channel, float energy_kev)
{
    uint8_t pkt[USB_PKT_SIZE];
    uint8_t kev_bytes[4];

    /* Copy float bytes (little-endian on Cortex-M) */
    memcpy(kev_bytes, &energy_kev, 4);

    pkt[0] = USB_PKT_START_EVENT;
    pkt[1] = channel;
    pkt[2] = kev_bytes[0];
    pkt[3] = kev_bytes[1];
    pkt[4] = kev_bytes[2];
    pkt[5] = kev_bytes[3];
    pkt[6] = calc_checksum(&pkt[1], 5);

    /* Ignore USBD_BUSY intentionally: if the USB IN endpoint is still
     * transmitting the previous packet, we drop this event rather than
     * blocking.  At 2 MHz USB FS the window is <1 ms and is extremely
     * rare in practice.  A more robust solution would use a FIFO. */
    (void)CDC_Transmit_FS(pkt, USB_PKT_SIZE);

    /* Update histogram trigger counter */
    if (energy_kev > 0.0f) {   /* ignore invalid events */
        s_event_count++;
        if (g_hist_mode == HIST_MODE_COUNT &&
            s_event_count >= g_hist_param) {
            s_hist_due    = true;
            s_event_count = 0;
        }
    }
}

/* ----------------------------------------------------------------
 * usb_comm_send_histogram_ready
 *
 * Sends a fixed 7-byte marker packet that the PC recognises as
 * the signal to display/update the histogram.
 *
 * Packet: [0xAA] [0xFF] [0x00 0x00 0x00 0x00] [checksum]
 * (channel=0xFF is reserved as the histogram-ready marker)
 * ---------------------------------------------------------------- */
void usb_comm_send_histogram_ready(void)
{
    uint8_t pkt[USB_PKT_SIZE] = {
        USB_PKT_START_EVENT, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    pkt[6] = calc_checksum(&pkt[1], 5);
    (void)CDC_Transmit_FS(pkt, USB_PKT_SIZE);

    /* Reset time window for TIME mode */
    s_time_start_ms = HAL_GetTick();
}

/* ----------------------------------------------------------------
 * usb_comm_poll_commands
 *
 * Checks if the USB CDC receive callback has filled s_rx_buf.
 * Parses one command per call.
 *
 * The CDC receive callback (in usbd_cdc_if.c, CDC_Receive_FS)
 * must copy data into s_rx_buf and set s_rx_ready = true.
 * Add this in usbd_cdc_if.c:
 *   extern uint8_t  usb_rx_buf[];
 *   extern uint16_t usb_rx_len;
 *   extern bool     usb_rx_ready;
 * ---------------------------------------------------------------- */
void usb_comm_poll_commands(void)
{
    if (!s_rx_ready) return;
    s_rx_ready = false;

    /* Minimum valid command = 7 bytes */
    if (s_rx_len < USB_PKT_SIZE) return;

    /* Validate start byte */
    if (s_rx_buf[0] != USB_PKT_START_CMD) return;

    /* Validate checksum */
    uint8_t cs = calc_checksum(&s_rx_buf[1], 5);
    if (cs != s_rx_buf[6]) return;

    uint8_t  cmd   = s_rx_buf[1];
    uint32_t param = 0;
    memcpy(&param, &s_rx_buf[2], 4);

    switch (cmd) {

        case USB_CMD_SET_COUNT:
            g_hist_mode  = HIST_MODE_COUNT;
            g_hist_param = param;
            s_event_count = 0;
            break;

        case USB_CMD_SET_TIME:
            g_hist_mode      = HIST_MODE_TIME;
            g_hist_param     = param;   /* seconds */
            s_time_start_ms  = HAL_GetTick();
            break;

        case USB_CMD_SET_CALIB: {
            float new_calib = 0.0f;
            memcpy(&new_calib, &param, 4);
            if (new_calib > 0.0f) g_s_t_ref = new_calib;
            break;
        }

        case USB_CMD_RESET:
            HAL_NVIC_SystemReset();
            break;

        default:
            break;
    }
}

/* ----------------------------------------------------------------
 * usb_comm_histogram_due
 * ---------------------------------------------------------------- */
bool usb_comm_histogram_due(void)
{
    /* COUNT mode — flag set inside usb_comm_send_event */
    if (g_hist_mode == HIST_MODE_COUNT && s_hist_due) {
        s_hist_due = false;
        return true;
    }

    /* TIME mode — check elapsed time */
    if (g_hist_mode == HIST_MODE_TIME) {
        uint32_t elapsed_s = (HAL_GetTick() - s_time_start_ms) / 1000;
        if (elapsed_s >= g_hist_param) {
            s_time_start_ms = HAL_GetTick();
            return true;
        }
    }

    return false;
}

/* ----------------------------------------------------------------
 * USB CDC receive hook
 * Add a call to this function from CDC_Receive_FS() in
 * usbd_cdc_if.c (inside the USER CODE section).
 *
 * void usb_comm_on_receive(uint8_t *buf, uint32_t len) must be
 * declared extern in usbd_cdc_if.c.
 * ---------------------------------------------------------------- */
void usb_comm_on_receive(uint8_t *buf, uint32_t len)
{
    if (len <= RX_BUF_SIZE) {
        memcpy(s_rx_buf, buf, len);
        s_rx_len   = (uint16_t)len;
        s_rx_ready = true;
    }
}
