#ifndef CONFIG_H
#define CONFIG_H

/* ================================================================
 * config.h
 *
 * Central configuration file for RADIOROC2 DAQ firmware.
 *
 * THIS FILE IS EDITED MANUALLY — not generated by CubeMX.
 *
 * Sections:
 *   1. Channel configuration
 *   2. Pin definitions
 *   3. I2C address
 *   4. ADC timing
 *   5. Timing constants
 *   6. Hold mode selection
 *   7. Trigger configuration
 *   8. Compensation algorithm
 *   9. Calibration
 * ================================================================ */

#include "stm32f7xx_hal.h"
#include <stdint.h>
#include <stdbool.h>

/* ================================================================
 * 1. CHANNEL CONFIGURATION
 *
 * List the ASIC channel numbers you want to use (0-63).
 * The firmware will automatically:
 *   - determine the highest channel (stops CK_READ early)
 *   - only sample ADC on active channels
 *   - skip all others during readout
 * ================================================================ */
#define ACTIVE_CHANNELS      { 0, 1, 2 }
#define NUM_ACTIVE_CHANNELS  3

/* ================================================================
 * 2. PIN DEFINITIONS
 *    Matches the schematic final_proj.kicad_sch
 * ================================================================ */

/* --- Analog inputs -------------------------------------------- */
#define ADC_HG_PIN           GPIO_PIN_4   /* PA4 → ADC1_IN4 → OUT_AMUXHG */
#define ADC_HG_PORT          GPIOA
#define ADC_LG_PIN           GPIO_PIN_5   /* PA5 → ADC2_IN5 → OUT_AMUXLG */
#define ADC_LG_PORT          GPIOA

/* --- NOR_T1OC — event interrupt trigger ----------------------- */
#define NOR_T1_PIN           GPIO_PIN_0   /* PA0 — EXTI0, falling edge   */
#define NOR_T1_PORT          GPIOA
#define NOR_T1_EXTI_IRQn     EXTI0_IRQn

/* --- CK_READ — TIM2_CH2 single pulse -------------------------- */
#define CK_READ_PIN          GPIO_PIN_1   /* PA1 — TIM2_CH2              */
#define CK_READ_PORT         GPIOA

/* --- CLK_SM_I2C — TIM1_CH1 continuous 2 MHz ------------------ */
#define CLK_SM_I2C_PIN       GPIO_PIN_8   /* PA8 — TIM1_CH1              */
#define CLK_SM_I2C_PORT      GPIOA

/* --- GPIO outputs (active low unless noted) ------------------- */
#define RSTN_READ_PIN        GPIO_PIN_1   /* PD1 — active low            */
#define RSTN_READ_PORT       GPIOD

#define RESET_N_PIN          GPIO_PIN_4   /* PD4 — active low, 20 ns     */
#define RESET_N_PORT         GPIOD

#define HOLDEXT_PIN          GPIO_PIN_2   /* PD2 — active high           */
#define HOLDEXT_PORT         GPIOD

#define RSTN_I2C_PIN         GPIO_PIN_0   /* PD0 — active low            */
#define RSTN_I2C_PORT        GPIOD

#define RSTN_SC_PIN          GPIO_PIN_7   /* PD7 — active low            */
#define RSTN_SC_PORT         GPIOD

/* --- GPIO inputs ---------------------------------------------- */
#define ERRORN_OC_PIN        GPIO_PIN_3   /* PD3 — active low, open col. */
#define ERRORN_OC_PORT       GPIOD

/* --- I2C (managed by HAL, listed for reference) --------------- */
#define SCL_PIN              GPIO_PIN_8   /* PB8 — I2C1_SCL              */
#define SDA_PIN              GPIO_PIN_9   /* PB9 — I2C1_SDA              */

/* ================================================================
 * 3. RADIOROC2 I2C ADDRESS
 *
 * CHIP_ID<0:3> = "0001" (hardwired on board)
 * 7-bit base address = 0x08
 * ================================================================ */
#define RADIOROC2_CHIP_ID    0x08

/* ================================================================
 * 4. ADC TIMING
 *
 * ADCCLK = APB2 / 6 = 108 MHz / 6 = 18 MHz
 * Sampling time for S&H output (slow DC through op-amp buffer):
 *   480 cycles = 26.7 µs
 * Conversion time (12-bit fixed):
 *   12 cycles  = 0.67 µs
 * Total per channel: 27.3 µs
 *
 * Temperature sensor sampling:
 *   84 cycles = 4.7 µs (STM32 datasheet minimum: 10 µs)
 * ================================================================ */
#define ADC_SAMPLING_CYCLES_SH    ADC_SAMPLETIME_480CYCLES
#define ADC_SAMPLING_CYCLES_TEMP  ADC_SAMPLETIME_84CYCLES

/* ================================================================
 * 5. TIMING CONSTANTS
 * ================================================================ */

/* Time to wait after RSTN_READ before first CK_READ pulse (µs) */
#define MUX_SETTLE_US        2

/* CK_READ pulse period — must be >= ADC total time + MUX settle  */
/* TIM2: prescaler=215, ARR=29 → 30 µs at 1 µs resolution        */
#define CK_READ_PERIOD_US    30

/* RESET_N pulse width — datasheet requires exactly 20 ns minimum  */
/* At 216 MHz: 1 cycle = 4.6 ns → 5 NOPs ≈ 23 ns                 */
#define RESET_N_PULSE_NOPS   5

/* S&H hold window — internal delay register values               */
/* delay=0xFF, slopeTrim=0xF → 255 × 0.85 ns × 15 ≈ 3.25 µs      */
#define ASIC_DELAY_VAL       0xFF
#define ASIC_SLOPE_TRIM      0x0F

/* ================================================================
 * 6. HOLD MODE SELECTION
 *
 * Choose ONE option and comment out the other.
 *
 * OPTION A — HOLD_MODE_INTERNAL:
 *   ASIC generates hold internally via delay register.
 *   selHoldExt = 0. HOLDEXT pin not used.
 *   WARNING: max hold = 3.25 µs, ADC needs 27.3 µs.
 *   Only viable if shaping time is reduced significantly.
 *
 * OPTION B — HOLD_MODE_EXTERNAL (recommended):
 *   STM32 controls hold duration via HOLDEXT pin (PD2).
 *   selHoldExt = 1. Guarantees ADC finishes before hold releases.
 * ================================================================ */
#define HOLD_MODE_INTERNAL   0
#define HOLD_MODE_EXTERNAL   1

/* >>> SELECT HERE — comment out the unused line <<< */
#define HOLD_MODE   HOLD_MODE_EXTERNAL   /* OPTION B — external hold (recommended) */
/* #define HOLD_MODE   HOLD_MODE_INTERNAL */ /* OPTION A — internal hold             */

/* ================================================================
 * 7. TRIGGER CONFIGURATION
 *
 * selTrig<1:0> = "01" → Local Low Threshold Time Trigger T1
 *   Each channel triggers only on its own signal (not global).
 *
 * selHoldExt set automatically based on HOLD_MODE above.
 *
 * Register value (Address 65, Subadd 12, bits [4:0]):
 *   OPTION B (external hold): bits = 1_01_00 = 0x14
 *   OPTION A (internal hold): bits = 0_01_00 = 0x04
 * ================================================================ */
#if HOLD_MODE == HOLD_MODE_EXTERNAL
    #define SELTRIG_REG_VALUE   0x14
#else
    #define SELTRIG_REG_VALUE   0x04
#endif

/* ================================================================
 * 8. COMPENSATION ALGORITHM
 *
 * PI feedback loop (PATH 1 — SiPM gain via InDAC):
 *   KP, KI        — proportional and integral gains.
 *                   Start with KP=0.15, KI=0.02.
 *                   Tune experimentally: increase KP until fast
 *                   response, add KI to remove steady-state error.
 *   V_SETPOINT    — target ADC count at calibration temperature.
 *                   Set this after first calibration measurement.
 *   DAC_BASELINE  — InDAC starting value at T_REF.
 *   DAC_MIN/MAX   — hardware limits of InDAC register (0-255).
 *   CONVERGENCE_THR — loop considered converged when
 *                   |Vpeak - V_SETPOINT| < this value (ADC counts).
 *   WARMUP_TICKS  — seconds to wait before enabling correction.
 *
 * LY(T) polynomial correction (PATH 2 — crystal light yield):
 *   T_REF         — calibration temperature (°C).
 *   LY_REF        — LY(27°C) from polynomial = 0.9999.
 * ================================================================ */
#define KP                   0.15f
#define KI                   0.02f
#define V_SETPOINT           2048        /* ADC counts — SET AFTER CALIBRATION    */
#define DAC_BASELINE         128         /* InDAC at T_REF                        */
#define DAC_MIN              0
#define DAC_MAX              255
#define CONVERGENCE_THR      60          /* ADC counts (~1.5% of full scale)      */
#define WARMUP_TICKS         5           /* seconds                               */

#define T_REF                27.0f       /* calibration temperature °C            */
#define LY_REF               0.9999f     /* LY(27°C) from polynomial              */

/* ================================================================
 * 9. CALIBRATION
 *
 * S_T_REF: ADC counts per keV at T_REF (27°C).
 *
 * How to calibrate:
 *   1. Place Cs-137 source (662 keV photopeak) near detector.
 *   2. Run system at 27°C until histogram shows clear photopeak.
 *   3. Read the ADC count at the photopeak centre.
 *   4. S_T_REF = photopeak_ADC_count / 662.0
 *   5. Update this value and recompile, OR send via USB command
 *      CMD_SET_CALIB (0x03) from the Python application.
 *
 * Placeholder value: 3.1 counts/keV — update after calibration.
 * ================================================================ */
#define S_T_REF              3.1f        /* ADC counts/keV — CALIBRATE EXPERIMENTALLY */

#endif /* CONFIG_H */
